version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app
      - db-data:/app/flask_app/engine
    ports:
      - 5000:5000
    command: ["python", "-m", "flask_app.app"]

volumes:
  db-data: